name: Monitor Lunchdrop

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'  # runs every 15 minutes (optional, adjust as needed)
  workflow_dispatch:  # allows manual triggering from GitHub UI

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # or your project’s version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lunchdrop Monitor
        run: |
          python monitor_lunchdrop.py
