name: Lunchdrop Monitor

on:
  schedule:
    - cron: "30 14 * * 1-5"   # weekdays 14:30 UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies & browsers
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install-deps
          python -m playwright install chromium

      - name: Run monitor
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          LOOKAHEAD_DAYS: ${{ secrets.LOOKAHEAD_DAYS }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          LUNCHDROP_EMAIL: ${{ secrets.LUNCHDROP_EMAIL }}
          LUNCHDROP_PASSWORD: ${{ secrets.LUNCHDROP_PASSWORD }}
          HEADLESS: "true"
          VERBOSE: "true"
          SEND_EMPTY_SLACK: "true"
          # Optional (only if you created these secrets):
          CSS_CARD_SELECTORS: ${{ secrets.CSS_CARD_SELECTORS }}
          MIN_CARD_COUNT: ${{ secrets.MIN_CARD_COUNT }}
        run: python monitor_lunchdrop.py
